config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'tables#search'

  resources :home, only: [:index]
  resources :tables, only: [:index, :show]

  # get :table, to: 'tables#show'
  get :search, controller: 'tables'
  get :build, controller: :tables
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :season
end

app/models/season.rb
class Season < ApplicationRecord
  belongs_to :show
  has_many :episodes, dependent: :destroy
end

app/models/show.rb
class Show < ApplicationRecord
  has_many :seasons, dependent: :destroy
  has_many :episodes, through: :seasons

  def full_title
    return "#{title} (#{year})" if year
    title
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/concerns/create_from_api_data.rb
module CreateFromApiData
  def create_from_api_data(show, ratings)
    show = Show.find_or_create_by(title: show[:title], imdb_id: show[:imdb_id], year: show[:year])
    show_data = ratings.payload
    
    show_data.each do |season, episodes|
      season = Season.create(number: season, show: show)
      
      episodes.each do |episode|
        Episode.create(imdb_rating: episode[:imdb_rating], imdb_id: episode[:imdb_id], season: season)
      end
    end

    show
  end
end

app/controllers/concerns/tables_helper.rb
module TablesHelper
  def create_from_api_data(show, ratings)
    show = Show.find_or_create_by(title: show[:title], imdb_id: show[:imdb_id])
    ratings = ratings.payload
    # debugger
    ratings.each do |season, episodes|
      season = Season.create(number: season, show: show)
      
      episodes.each do |episode|
        Episode.create(imdb_rating: episode, season: season)
      end
    end

    show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  include CreateFromApiData

  def index
    query = params[:search]
    @pagy, @shows = pagy(Show.ransack(title_cont: query).result(distinct: true))
    @api_shows = MovieDatabaseAlternativeApiService.new({query: query}).get_results.results
  end

  def show
    @show_data = Show.find(params[:id])
  end

  def build
    title = params[:title]
    imdb_id = params[:imdb_id]
    year = params[:year]
    show_data = { title: title, imdb_id: imdb_id, year: year }

    @show = Show.find_by_imdb_id(imdb_id)
    if @show.present?
      redirect_to table_path(@show), notice: 'Oops, it already built!'
      return
    else
      ratings_data = MoviesDatabaseApiService.new({ imdb_id: show_data[:imdb_id] }).get_seasons_episodes_ratings
      @show = create_from_api_data(show_data, ratings_data)
      if @show.present?
        redirect_to table_path(@show), notice: 'Table was built successfully!'
      end
    end

  end

  def search
    @shows = Show.ransack(title_cont: params[:q]).result(distinct: true)

    respond_to do |format|
      format.html {}
      format.json{ @shows = @shows.limit(5) }
    end
  end

  private

    def table_params
      params.fetch(:table, {}).permit(:search)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tables_helper.rb
module TablesHelper
  def generate_table(data)
    seasons = {}
    data.seasons.each do |s|
      seasons[s.number] = s.episodes.map{|e| { imdb_rating: e.imdb_rating, imdb_id: e.imdb_id } }
    end

    longest = seasons.values.max_by(&:length).length
    range = (1..longest).to_a

    table = []

    top_row = seasons.keys.map{ |s| "<th  style='color: white; background-color: black; text-align: center;' title='season #{s.to_s}'>" + s.to_s + '</th>' }
    table.append('<thead><th style="color: white; background-color: black; text-align: center;"></th>' + top_row.join('') + '</thead>')

    range.each do |i|
      row = ["<th style='color: white; background-color: black; text-align: center;' title='episode #{i}'>#{i}</th>"]
      seasons.keys.each do |key|
        imdb_rating = seasons[key][i-1].try(:[], :imdb_rating)
        imdb_id = seasons[key][i-1].try(:[], :imdb_id)
        if imdb_rating
          td = "<td style='#{highlight_cell(imdb_rating)} cursor: pointer;' onclick=#{generate_onclick(imdb_id)} title='season #{key} episode #{i}'>#{imdb_rating}</t=></td>"
        else
          td = "<td></td>"
        end
        row.append(td)
      end

      table.append("<tr>" + row.join('') + "</tr>")
    end

    
    "<table class='table table-bordered'>#{table.join('')}</table>".html_safe
  end

  def highlight_cell(val)
    if val >= 8.6
      color = 'MediumSeaGreen'
    elsif val >= 7.6
      color = 'yellow'
    elsif val >= 6.6
      color = 'orange'
    elsif val >= 5.6
      color = 'IndianRed'
    else
      color = 'MediumSlateBlue'
    end

    "text-align: center; background-color: #{color};"
  end

  def generate_onclick(imdb_id)
    "window.open('https://www.imdb.com/title/#{imdb_id}/')"
  end

  def build_table_link(api_show)
    link_to("Build for '#{api_show[:title]} (#{api_show[:year]})'", build_path(title: api_show[:title], imdb_id: api_show[:imdb_id], year: api_show[:year]))
  end
end

app/views/home/index.html.erb
<h2>Home</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Episode Ratings Table</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/easy-autocomplete/1.3.5/easy-autocomplete.min.css" integrity="sha512-TsNN9S3X3jnaUdLd+JpyR5yVSBvW9M6ruKKqJl5XiBpuzzyIMcBavigTAHaH50MJudhv5XIkXMOwBL7TbhXThQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'flash_autoclose', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/easy-autocomplete/1.3.5/jquery.easy-autocomplete.min.js" integrity="sha512-Z/2pIbAzFuLlc7WIt/xifag7As7GuTqoBbLsVTgut69QynAIOclmweT6o7pkxVoGGfLcmPJKn/lnxyMNKBAKgg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

  </head>

  <body>
    <% if notice %>
      <div id="notice_wrapper">
        <p class="notice"><%= notice %></p>
      </div>
    <% elsif alert %>
      <div id="notice_wrapper">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <div class="container">
      <%= render partial: 'shared/nav' %>
      <%= yield %>
    </div>

    <script>
    $(document).ready(() => {
      setTimeout(function () {
        $("#notice_wrapper").fadeOut("slow", function () {
          $(this).remove();
        });
      }, 2000);
    });
    </script>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'ERT', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Tables', tables_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/tables/_markers.html.erb
<p class="mx-1 px-1" style="background-color: MediumSeaGreen;">great</p>
<p class="mx-1 px-1" style="background-color: yellow;">good</p>
<p class="mx-1 px-1" style="background-color: orange;">ok</p>
<p class="mx-1 px-1" style="background-color: IndianRed;">bad</p>
<p class="mx-1 px-1" style="background-color: MediumSlateBlue;">garbage</p>

app/views/tables/index.html.erb
<div class="container">
    <div class="d-flex flex-column text-center justify-content-center table-responsive">
        <div>
            <% if @shows.any? %>
                <h3>Available Tables</h3>
            <% end %>
            <% @shows.each do |show| %>
                <div>
                 <%= link_to(show.full_title, table_path(show)) %>
                </div>
            <% end %>
            <% if params[:search] %>
                <h3>Tables to Build</h3>
                <% @api_shows&.each do |api_show| %>
                    <div>
                        <%= build_table_link(api_show) %>
                    </div>
                <% end %>
            <% end %>
        </div>
    </div>
      <%# Note the double equals sign "==" which marks the output as trusted and html safe: %>
    <div class="d-flex justify-content-center mt-5">
        <%= pagy_bootstrap_nav(@pagy).html_safe if @pagy.count > 1 %>
    </div>
</div>

app/views/tables/search.html.erb
<div class="container">
    <div class="d-flex flex-column text-center align-items-center">
        <h2>Search</h2>
        <%= form_with url: tables_path, local: true, method: 'GET' do %>
            <%= text_field_tag :search, params[:search], id: 'search' %>
            <%= submit_tag 'Search', class: 'btn btn-primary mt-2' %>
        <% end %>
    </div>

    <div class="d-flex flex-column text-center justify-content-center table-responsive">
        <div>
            <%# @show_data.each do |show| %>
                <%#= show.title %>
            <%# end %>
        </div>
    </div>
</div>

<script>
document.addEventListener("turbolinks:load", () => {
    $input = $("#search")
    let options = {
        getValue: "title",
        url: function(phrase){
            return '/search.json?q=' + phrase;
        },
        categories: [
            { listLocation: "shows" }
        ],
        list: {
            onChooseEvent: () => {
                let url = $input.getSelectedItemData().url;
                $input.val('');
                Turbolinks.visit(url);
            }
        }
    };

    $input.easyAutocomplete(options);
})
</script>

app/views/tables/show.html.erb
<div class="container">
    <div class="d-flex flex-column text-center justify-content-center table-responsive">
        <div class="d-flex justify-content-around">
            <h2><%= @show_data&.full_title %></h2>
            <div class="d-flex justify-content-start mt-2">
                <%= render 'markers' %>
            </div>
        </div>
        <%= generate_table(@show_data) %>
    </div>
</div>